version: '3.8'

services:
  kasa-smartplug-exporter:
    container_name: kasa-smartplug-exporter
    restart: unless-stopped
    network_mode: host
    # Can use pre-built image or build locally,
    # To build locally, uncomment the build line and comment out the image line
    image: ghcr.io/vaibzzz123/kasa-smartplug-exporter:latest
    #build: .
    environment:
    # All environment variables are loaded from .env file in this case, or can specify them here directly
      - PORT=${PORT:-4467}
      - POLL_INTERVAL=${POLL_INTERVAL:-10}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - KASA_USERNAME=${KASA_USERNAME}
      - KASA_PASSWORD=${KASA_PASSWORD}
      - KASA_MODELS=${KASA_MODELS}
    volumes:
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:4467/metrics')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
